# Generated by Django 2.1.7 on 2019-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=400)),
                ('payment_method', models.CharField(max_length=400)),
                ('payment_date', models.CharField(max_length=400)),
                ('items', models.TextField()),
                ('fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('img_link', models.TextField()),
            ],
        ),
    ]
