# Generated by Django 2.1.7 on 2019-03-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_store', '0002_auto_20190305_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
